name: flutter_secure_file_storage
description: An implementation for flutter secure file storage. For example keychain has a soft limit of 4kb. Using the file system instead we can store much larger content
version: 0.0.7
homepage: https://github.com/icapps/flutter_secure_file_storage

environment:
  sdk: ">=2.14.0 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  device_info_plus: ^3.2.0
  flutter:
    sdk: flutter
  flutter_key_value_file_storage: ^0.0.2
  flutter_secure_storage: ^5.0.2
  path: ^1.8.0
  path_provider: ^2.0.8
  pointycastle: ^3.4.0

dev_dependencies:
  build_runner: ^2.1.7
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  mockito: ^5.0.17

flutter:
  plugin:
    platforms:
      android:
        package: com.icapps.flutter_secure_file_storage
        pluginClass: SecureFileStoragePlugin
      ios:
        pluginClass: FlutterSecureFileStoragePlugin
